### ISSUE TITLE
Roadmap: WDRO for Mean-Risk Portfolio Optimization

### ISSUE THREAD

**Issue by wazizian** [iutzeler/skwdro#15]
This issue is a roadmap for the internship of Alan.
### Reproduce existing results
- [x] Solve the WDRO problem using a convex solver and reproduce the out-of-sample plots of D. Kuhn.
### Regularized WDRO
- [ ] Implement the dual loss and a sampler on the simplex
- [ ] Interface with a MWU-based optimization algorithm
- [ ] Compare with above
### Extensions
- [ ] Try with different costs, e.g. log
- [x] Study how to tune the radius: interface with and leverage [scikit-learn model selection methods](https://scikit-learn.org/stable/modules/grid_search.html). Compare with Blanchet's statistical approach (and maybe [a recent work](https://github.com/stellatogrp/lropt)).
- [ ] Experiment in an online setting.
